dist: xenial
sudo: required
language: python

python:
  - "3.6"

services:
  - docker

script:
  - docker-compose -f docker-compose.test.yml up --exit-code-from connector_test

after_success:
  - sh deploy_dockerhub.sh