# Testing compose. Execute by running:
# ./test.sh
version: '3.6'
services:
  influxdb_test:
    image: influxdb
    container_name: influxdb_test
    expose:
      - "8083"
      - "8086"
      - "8090"

  connector_test:
    container_name: connector_test
    build: .
    links:
      - influxdb_test
    volumes:
      - ./:/connector
    command: /bin/bash -c "source activate connector && pytest -v"
