# DEV SETUP
# Connector is created directly from docker file and
# the app/ volume is mounted inside the container for debugging
version: '3.1'
services:
  connector:
    container_name: connector
    build: .
    links:
      - influxdb
    volumes:
      - ./connector:/connector
    restart: unless-stopped

  influxdb:
    image: influxdb
    container_name: influxdb
    restart: unless-stopped
