# PRODUCTION SETUP
# CONNECTOR is deployed using the latest container image in
# docker hub (https://cloud.docker.com/u/encresearch/repository/docker/encresearch/mqtt-connector).
# If a new :latest image is pushed, watchtower will automatically shutdown the container currently
# running, update it and re-deploy it.

version: '3.1'

volumes:
  influx_data: {}
    
services:
  connector:
    container_name: connector
    image: encresearch/mqtt-connector:latest
    restart: unless-stopped
       
  influxdb:
    image: influxdb:1.7
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    volumes:
      # Data persistency
      - influx_data:./var/lib/influxdb
    restart: unless-stopped

  watchtower: # checks for changes in any of the installed images (on the latest tag)
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # mounts docker socket to interact with Docker's API
    command: --interval 300 # Checks for changes every 5 minutes
    restart: unless-stopped
