# Testing compose. Execute by running:
# ./test.sh
version: '3.6'

services:

  connector_test:
    container_name: connector_test
    build:
      context: ./
      dockerfile: Dockerfile
      target: testing
    links:
      - influxdb_test
    environment:
      - DB_HOST=influxdb_test

  influxdb_test:
    image: influxdb:1.7
    container_name: influxdb_test
    expose:
      - "8083"
      - "8086"
      - "8090"
