# DEV SETUP
# Connector is created directly from docker file and
# the app/ volume is mounted inside the container for debugging
version: '3.1'
services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 80:3000
    links:
      - influxdb
    env_file:
      - ./etc/grafana.conf
    restart: unless-stopped

  connector:
    container_name: connector
    build: .
    links:
      - influxdb
    volumes:
      - ./connector:/connector
    restart: unless-stopped

  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    restart: unless-stopped