# DEV SETUP
# Connector is created directly from docker file and
# the app/ volume is mounted inside the container for debugging

version: '3.1'

volumes:
  grafana_data: {}
  influx_data: {}
    
services:

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 80:3000
    links:
      - influxdb
    env_file:
      - ./etc/grafana.conf
    volumes:
      # Makes sure data is stored in host only if 
      # postgres is still not configured in the grafana.env file
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

  connector:
    container_name: connector
    build: .
    links:
      - influxdb
    volumes:
      - ./app:/app
    restart: unless-stopped

  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    volumes:
      # Data persistency
      - influx_data:/var/lib/influxdb
    restart: unless-stopped