# DEV SETUP
# Connector is created directly from docker file and
# the app/ volume is mounted inside the container for debugging
version: '3.6'

volumes:
  influx_data: {}

services:

  connector:
    container_name: connector
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    links:
      - influxdb
    volumes:
      - ./connector:/connector
    restart: unless-stopped

  influxdb:
    image: influxdb:1.7
    container_name: influxdb
    expose:
      - "8083"
      - "8086"
      - "8090"
    volumes:
      - influx_data:/var/lib/influxdb
    restart: unless-stopped
