name: Connector CI Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Conector PyTests
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Run Tests
        run: docker-compose -f docker-compose.test.yml up --build --exit-code-from connector_test
